apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger
  annotations:
    checksum/conf: {{ include (print $.Template.BasePath "/configmap-swagger.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger 
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
      - image: swaggerapi/swagger-ui:v3.51.1
        name: swagger
        env:
        - name: BASE_URL
          value: /docs
        volumeMounts:
        - name: swagger
          mountPath: /app/swagger.json
          subPath: swagger.json
      volumes:
      - name: swagger
        configMap:
          name: swagger
      restartPolicy: Always
